server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://121.4.43.41:3306/weixinBackEnd
    username: gjc
    password: GE66ge66
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiangpin.model.po