spring:
  datasource:
    url: jdbc:mysql://121.4.43.41:3306/weixinBackEnd
    username: littleb
    password: mymmyyds
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml